### ISSUE TITLE
about auto_diff_eigs.py

### ISSUE THREAD

**Issue by Bobbyztz** [ranshiju/Python-for-Tensor-Network-Tutorial#2]
v1.tensor = v1.tensor - lr * v1.grad
    v1.grad.tensor.zero_()

shoud be

    v1.data= v1.data- lr * v1.grad
    v1.grad.data.zero_()

**Comment by ranshiju** [comment]
You are right. Thanks :)

Best,
Shi-Ju Ran

**Comment by Bobbyztz** [comment]
> 

Glad to do so : ) Thanks for your tutorial!
